

services:
  mysql:
    image: mysql:8.0
    container_name: steam-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: steamdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/sql:/docker-entrypoint-initdb.d
    networks:
      - steam-network

  app:
    build: .
    container_name: steam-app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - steam-network

volumes:
  db_data:

networks:
  steam-network:
    driver: bridge
